"use strict";(()=>{var e={};e.id=9096,e.ids=[9096],e.modules={53524:e=>{e.exports=require("@prisma/client")},72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},46034:(e,t,i)=>{i.r(t),i.d(t,{originalPathname:()=>f,patchFetch:()=>h,requestAsyncStorage:()=>x,routeModule:()=>p,serverHooks:()=>m,staticGenerationAsyncStorage:()=>g});var r={};i.r(r),i.d(r,{POST:()=>d});var s=i(49303),a=i(88716),n=i(60670),o=i(87070),u=i(9487),l=i(70446),c=i(20667);async function d(e,{params:t}){let i=(0,l.cw)();if(!(0,l.vz)()&&(!i||i.workspaceSlug!==t.workspaceSlug))return o.NextResponse.json({error:"Unauthorized"},{status:401});let r=await u._.workspace.findUnique({where:{slug:t.workspaceSlug}});if(!r)return o.NextResponse.json({error:"Workspace not found"},{status:404});let s=await u._.exerciseLibraryItem.findFirst({where:{workspaceId:r.id,title:{contains:"Varexia",mode:"insensitive"}}});if(s)return o.NextResponse.json({message:"Varexia-Fallstudie bereits vorhanden",item:s});let a=await u._.exerciseLibraryItem.create({data:{workspaceId:r.id,title:"Varexia SE – Strategische Unternehmensanalyse",exerciseType:"case_study",tags:["Fallstudie","Strategie","C-Level","Turnaround","Finanzanalyse","Portfolio-Management","Varexia"],targetLevels:["C-Level","Vorstand","Director"],languagesAvailable:["DE","EN"],qualityStatus:"validated",metadataJson:{caseStudyId:c.Ix.id,companyName:c.Ix.name,description:c.Ix.description,metrics:c.Ix.metrics,businessUnitCount:c.Ix.businessUnits.length,businessUnits:c.Ix.businessUnits.map(e=>({id:e.id,name:e.name,revenue:e.revenue,margin:e.margin,tension:e.tension})),emailCount:c.Ix.emails.length,exerciseModules:c.c6.map(e=>({id:e.id,title:e.title,subtitle:e.subtitle,type:e.type,difficulty:e.difficulty,description:e.description})),assessmentQuestions:c.nw,duration:120,instructions:`Als Kandidat f\xfcr die Position des Chief Strategy Officer (CSO) bei Varexia SE f\xfchren Sie eine umfassende strategische Analyse durch. 

Sie erhalten:
- Finanzdaten und KPIs aller ${c.Ix.businessUnits.length} Gesch\xe4ftsbereiche
- Vertrauliche E-Mails von Vorstand und Aufsichtsrat
- Bilanz- und Ergebnisdaten

Aufgabe: Entwickeln Sie eine Turnaround-Strategie mit klaren Handlungsempfehlungen f\xfcr den Aufsichtsrat.

Bewertungskriterien: Strategische Tiefe, finanzielle Urteilsf\xe4higkeit, Entscheidungsf\xe4higkeit unter Unsicherheit.`}},include:{_count:{select:{variants:!0}}}});return o.NextResponse.json({message:"Varexia-Fallstudie erfolgreich angelegt",item:a},{status:201})}let p=new s.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/w/[workspaceSlug]/exercise-library/seed-varexia/route",pathname:"/api/w/[workspaceSlug]/exercise-library/seed-varexia",filename:"route",bundlePath:"app/api/w/[workspaceSlug]/exercise-library/seed-varexia/route"},resolvedPagePath:"/home/runner/workspace/app/api/w/[workspaceSlug]/exercise-library/seed-varexia/route.ts",nextConfigOutput:"standalone",userland:r}),{requestAsyncStorage:x,staticGenerationAsyncStorage:g,serverHooks:m}=p,f="/api/w/[workspaceSlug]/exercise-library/seed-varexia/route";function h(){return(0,n.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:g})}}};var t=require("../../../../../../webpack-runtime.js");t.C(e);var i=e=>t(t.s=e),r=t.X(0,[9276,1615,5972,1989],()=>i(46034));module.exports=r})();